// <auto-generated />
using System;
using BingoEvent.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIfolder.Migrations
{
    [DbContext(typeof(BingoContext))]
    [Migration("20260302084434_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BingoEvent.API.Data.BingoBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BingoBoards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Bingo Board"
                        });
                });

            modelBuilder.Entity("BingoEvent.API.Data.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BingoBoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("WelcomePageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BingoBoardId");

                    b.HasIndex("WelcomePageId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BingoEvent.API.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Game"
                        });
                });

            modelBuilder.Entity("BingoEvent.API.Data.WelcomePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WelcomePages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Welcome Page"
                        });
                });

            modelBuilder.Entity("BingoEvent.API.Data.Event", b =>
                {
                    b.HasOne("BingoEvent.API.Data.BingoBoard", "BingoBoard")
                        .WithMany()
                        .HasForeignKey("BingoBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BingoEvent.API.Data.WelcomePage", "WelcomePage")
                        .WithMany()
                        .HasForeignKey("WelcomePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BingoBoard");

                    b.Navigation("WelcomePage");
                });

            modelBuilder.Entity("BingoEvent.API.Data.Game", b =>
                {
                    b.HasOne("BingoEvent.API.Data.Event", null)
                        .WithMany("Games")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("BingoEvent.API.Data.Event", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
